#============================== Network device ================================
#We monitor any devices on the host OS. For OSX this is the VM hosting Docker.
packetbeat.interfaces.device: any

#================================== Flows =====================================
packetbeat.flows:
  enabled: true
  timeout: 30s
  period: 10s

#========================== Transaction protocols =============================
packetbeat.protocols:
- type: icmp
  enabled: true

# - type: dns
  # ports: [53]

- type: http
  ports: [80, 8080, 5000, 5601, 9200, 8081, 8002]
  send_headers: true
  send_all_headers: true

- type: tls
  ports: [443]
  send_certificates: false

# packetbeat.protocols.memcache:
#   ports: [11211]
# packetbeat.protocols.mysql:
#   ports: [3306]
# packetbeat.protocols.pgsql:
#   ports: [5432]
# packetbeat.protocols.redis:
#   ports: [6379]
# packetbeat.protocols.thrift:
#   ports: [9090]
# packetbeat.protocols.mongodb:
#   ports: [27017]
# packetbeat.protocols.cassandra:
#   ports: [9042]

#=========================== Monitored processes ==============================
packetbeat.procs:
  enabled: false
  monitored:
    - process: pgsql
      cmdline_grep: postgres

#================================ Processors ===================================
# For example, you can use the following processors to keep the fields that
# contain CPU load percentages, but remove the fields that contain CPU ticks
# values:
processors:
- include_fields:
   fields: ["cpu"]
- drop_fields:
   fields: ["cpu.user", "cpu.system"]
# The following example drops the events that have the HTTP response code 200:
- drop_event:
   when:
      equals:
          http.code: 200
# The following example enriches each event with metadata from the cloud provider about the host machine.
- add_docker_metadata:
   host: "unix:///var/run/docker.sock"
- add_cloud_metadata: ~
- add_locale: ~

logging.to_files: false

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]
  # username: ${ELASTICSEARCH_USERNAME}
  # password: ${ELASTICSEARCH_PASSWORD}

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}:5601"
  # username: ${ELASTICSEARCH_USERNAME}
  # password: ${ELASTICSEARCH_PASSWORD}

#============================== Xpack Monitoring ===============================
monitoring.enabled: true
# xpack.monitoring:
#   enabled: true
#   elasticsearch: