---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/7.17/docker/data/logstash/config/logstash-full.yml
#
http.host: 0.0.0.0

node.name: logstash

# X-Pack Monitoring
# https://www.elastic.co/guide/en/logstash/7.10/monitoring-logstash.html
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.enabled: true
# xpack.monitoring.elasticsearch.username: elastic
# xpack.monitoring.elasticsearch.password: changeme