heartbeat.monitors:
#Monitor all containers using an icmp ping
- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: ["filebeat","metricbeat","packetbeat","elasticsearch","kibana"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  wait: 1s

#Monitor the Elasticsearch instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://elasticsearch:9200"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  # username: '${ES_USERNAME:elastic}'
  # password: '${ES_PASSWORD:changeme}'
  check.request:
    method: "GET"
  check.response:
    status: 200

#Monitor the Kibana instance.
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://kibana:5601"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 3s
  check.request:
    method: "GET"
  check.response:
    status: 200
# - type: http
#   schedule: '@every 5s'
#   urls:
#     - http://elasticsearch:9200
#     - http://kibana:5601

# - type: icmp
#   schedule: '@every 5s'
#   hosts:
#     - elasticsearch
#     - kibana

processors:
- add_cloud_metadata:
- add_docker_metadata: ~

logging.to_files: false

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]
  # username: ${ELASTICSEARCH_USERNAME}
  # password: ${ELASTICSEARCH_PASSWORD}

#============================== Dashboards =====================================
# setup.dashboards:
  # enabled: true

#============================== Kibana =========================================
# setup.kibana:
  # host: "${KIBANA_HOST}:5601"
  # username: ${ELASTICSEARCH_USERNAME}
  # password: ${ELASTICSEARCH_PASSWORD}

#============================== Xpack Monitoring ===============================
monitoring.enabled: true
# xpack.monitoring:
#   enabled: true
#   elasticsearch: